name: 'deploy'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: NPM Target
        uses: anna-money/github-actions-npm@v4
        with:
          target: 'build-ui'

      - name: Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: 'ssh://dokku@tinygo.link:22/go-dutch'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
