name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: 'ssh://dokku@tinygo.link:22/go-dutch'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
